# -*- coding: utf-8 -*-
"""module7_knn-regr-scikit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSQ7NumQ1mcSbEaTSWtdWG3bU3sLNLrY
"""

import numpy as np
from sklearn.neighbors import KNeighborsRegressor

def read_positive_int(prompt):
    while True:
        try:
            v = int(input(prompt))
            if v > 0:
                return v
        except ValueError:
            pass
        print("Please enter a positive integer.")

def read_float(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("Please a number.")

def main():

    N = read_positive_int("Enter N number of points: ")
    k = read_positive_int("Enter k: ")

    if k > N:
        print("Error....... k must be <= N.")
        return

    xs = np.empty(N, dtype=float)
    ys = np.empty(N, dtype=float)

    for i in range(N):
        xs[i] = read_float(f"Enter x for point {i+1}: ")
        ys[i] = read_float(f"Enter y for point {i+1}: ")

    X_train = xs.reshape(-1, 1)
    y_train = ys


    model = KNeighborsRegressor(
        n_neighbors=k,
        weights="uniform",
        metric="euclidean"
    )
    model.fit(X_train, y_train)

    X_query = read_float("Enter X (query point): ")
    y_pred = model.predict(np.array([[X_query]]))[0]

    variance = float(np.var(ys))
    print("Prediction:", y_pred)
    print("Variance:", variance)

if __name__ == "__main__":
    main()