# -*- coding: utf-8 -*-
"""module6_knn-regr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hY57t8BwU9cAUPwAabm0oMjv_T22jGVK
"""



import numpy as np

def read_positive_int(prompt: str) -> int:
    while True:
        try:
            v = int(input(prompt))
            if v > 0:
                return v
        except ValueError:
            pass
        print("Please enter a positive integer")

def read_float(prompt: str) -> float:
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("Please enter a valid number.")

def main():
    # Read N and k
    N = read_positive_int("Enter N (number of points, positive integer): ")
    k = read_positive_int("Enter k (number of neighbors, positive integer): ")

    # Read N (x,y) points
    xs = np.empty(N, dtype=float)
    ys = np.empty(N, dtype=float)

    for i in range(N):
        xs[i] = read_float(f"Enter x for point {i+1}: ")
        ys[i] = read_float(f"Enter y for point {i+1}: ")

    # Read query X
    X = read_float("Enter X (query point): ")

    # Validate k
    if k > N:
        print("Error: k must be less than or equal to N.")
        return

    # Distances
    dists = np.abs(xs - X)
    knn_idx = np.argsort(dists, kind="mergesort")[:k]

    # MEAN of neighbors
    y_pred = float(np.mean(ys[knn_idx]))

    # Y
    print(y_pred)

if __name__ == "__main__":
    main()